# Generated by Django 5.0.2 on 2024-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_House', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseowner',
            name='unlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='houseowner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
