# Generated by Django 5.0.2 on 2024-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_House', '0002_houseowner_unlock_alter_houseowner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseowner',
            name='attempt',
            field=models.IntegerField(default=3),
        ),
    ]
