# Generated by Django 5.0.2 on 2024-02-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_House', '0003_houseowner_attempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseowner',
            old_name='password',
            new_name='password_1',
        ),
        migrations.RemoveField(
            model_name='houseowner',
            name='email',
        ),
        migrations.AddField(
            model_name='houseowner',
            name='password_2',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
